In [2]:
import pandas as pd

# save filepath to variable for easier access
melbourne_file_path = "C:\\Users\\chinm\\Downloads\\data.csv"
# read the data and store data in DataFrame titled melbourne_data
melbourne_data = pd.read_csv(melbourne_file_path) 
# print a summary of the data in Melbourne data
melbourne_data.describe()

,nose_x,nose_y,neck_x,neck_y,Rshoulder_x,Rshoulder_y,Relbow_x,Relbow_y,Rwrist_x,RWrist_y,...,LAnkle_x,LAnkle_y,REye_x,REye_y,LEye_x,LEye_y,REar_x,REar_y,LEar_x,LEar_y
count,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,...,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000
mean,0.466373,0.473390,0.468822,0.535980,0.430729,0.522919,0.409834,0.568567,0.412682,0.590159,...,0.498885,0.899289,0.433238,0.437930,0.433907,0.432555,0.392328,0.419229,0.427799,0.423581
std,0.162359,0.126528,0.160529,0.115908,0.178459,0.150700,0.187246,0.198410,0.194318,0.236794,...,0.164975,0.116257,0.191952,0.167376,0.197945,0.174294,0.210509,0.196563,0.214556,0.191327
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.330000,0.390000,0.340000,0.460000,0.310000,0.460000,0.280000,0.520000,0.290000,0.500000,...,0.380000,0.890000,0.310000,0.390000,0.320000,0.390000,0.270000,0.390000,0.320000,0.390000
50%,0.490000,0.440000,0.490000,0.500000,0.460000,0.500000,0.440000,0.590000,0.440000,0.650000,...,0.510000,0.910000,0.460000,0.440000,0.480000,0.410000,0.440000,0.440000,0.480000,0.410000
75%,0.590000,0.460000,0.590000,0.520000,0.560000,0.540000,0.540000,0.630000,0.560000,0.700000,...,0.610000,0.940000,0.570000,0.460000,0.590000,0.460000,0.560000,0.460000,0.590000,0.460000
max,0.830000,0.720000,0.830000,0.740000,0.820000,0.740000,0.840000,0.850000,0.850000,0.890000,...,0.850000,0.980000,0.820000,0.720000,0.830000,0.700000,0.820000,0.720000,0.840000,0.700000

melbourne_data.head()

In [3]:
melbourne_data.columns

Index(['nose_x', 'nose_y', 'neck_x', 'neck_y', 'Rshoulder_x', 'Rshoulder_y',
       'Relbow_x', 'Relbow_y', 'Rwrist_x', 'RWrist_y', 'LShoulder_x',
       'LShoulder_y', 'LElbow_x', 'LElbow_y', 'LWrist_x', 'LWrist_y', 'RHip_x',
       'RHip_y', 'RKnee_x', 'RKnee_y', 'RAnkle_x', 'RAnkle_y', 'LHip_x',
       'LHip_y', 'LKnee_x', 'LKnee_y', 'LAnkle_x', 'LAnkle_y', 'REye_x',
       'REye_y', 'LEye_x', 'LEye_y', 'REar_x', 'REar_y', 'LEar_x', 'LEar_y',
       'class'],
      dtype='object')

In [4]:
melbourne_data.head()

,nose_x,nose_y,neck_x,neck_y,Rshoulder_x,Rshoulder_y,Relbow_x,Relbow_y,Rwrist_x,RWrist_y,...,LAnkle_y,REye_x,REye_y,LEye_x,LEye_y,REar_x,REar_y,LEar_x,LEar_y,class
0,0.55,0.46,0.54,0.52,0.51,0.52,0.52,0.57,0.54,0.50,...,0.91,0.54,0.46,0.00,0.00,0.52,0.46,0.55,0.46,stand
1,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.61,0.50,0.65,...,0.91,0.54,0.46,0.55,0.46,0.52,0.46,0.56,0.46,stand
2,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.59,0.50,0.65,...,0.91,0.54,0.46,0.55,0.46,0.52,0.46,0.56,0.46,stand
3,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.59,0.50,0.65,...,0.91,0.54,0.44,0.55,0.44,0.52,0.46,0.55,0.46,stand
4,0.54,0.46,0.54,0.52,0.51,0.52,0.50,0.59,0.51,0.65,...,0.91,0.54,0.44,0.55,0.44,0.52,0.46,0.55,0.46,stand

In [5]:
melbourne_features = ['nose_x', 'nose_y', 'neck_x', 'neck_y', 'Rshoulder_x', 'Rshoulder_y',
       'Relbow_x', 'Relbow_y', 'Rwrist_x', 'RWrist_y', 'LShoulder_x',
       'LShoulder_y', 'LElbow_x', 'LElbow_y', 'LWrist_x', 'LWrist_y', 'RHip_x',
       'RHip_y', 'RKnee_x', 'RKnee_y', 'RAnkle_x', 'RAnkle_y', 'LHip_x',
       'LHip_y', 'LKnee_x', 'LKnee_y', 'LAnkle_x', 'LAnkle_y', 'REye_x',
       'REye_y', 'LEye_x', 'LEye_y', 'REar_x', 'REar_y', 'LEar_x', 'LEar_y']
x = melbourne_data[melbourne_features]

In [6]:
x.describe()

,nose_x,nose_y,neck_x,neck_y,Rshoulder_x,Rshoulder_y,Relbow_x,Relbow_y,Rwrist_x,RWrist_y,...,LAnkle_x,LAnkle_y,REye_x,REye_y,LEye_x,LEye_y,REar_x,REar_y,LEar_x,LEar_y
count,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,...,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000,2826.000000
mean,0.466373,0.473390,0.468822,0.535980,0.430729,0.522919,0.409834,0.568567,0.412682,0.590159,...,0.498885,0.899289,0.433238,0.437930,0.433907,0.432555,0.392328,0.419229,0.427799,0.423581
std,0.162359,0.126528,0.160529,0.115908,0.178459,0.150700,0.187246,0.198410,0.194318,0.236794,...,0.164975,0.116257,0.191952,0.167376,0.197945,0.174294,0.210509,0.196563,0.214556,0.191327
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.330000,0.390000,0.340000,0.460000,0.310000,0.460000,0.280000,0.520000,0.290000,0.500000,...,0.380000,0.890000,0.310000,0.390000,0.320000,0.390000,0.270000,0.390000,0.320000,0.390000
50%,0.490000,0.440000,0.490000,0.500000,0.460000,0.500000,0.440000,0.590000,0.440000,0.650000,...,0.510000,0.910000,0.460000,0.440000,0.480000,0.410000,0.440000,0.440000,0.480000,0.410000
75%,0.590000,0.460000,0.590000,0.520000,0.560000,0.540000,0.540000,0.630000,0.560000,0.700000,...,0.610000,0.940000,0.570000,0.460000,0.590000,0.460000,0.560000,0.460000,0.590000,0.460000
max,0.830000,0.720000,0.830000,0.740000,0.820000,0.740000,0.840000,0.850000,0.850000,0.890000,...,0.850000,0.980000,0.820000,0.720000,0.830000,0.700000,0.820000,0.720000,0.840000,0.700000

In [7]:
melbourne_features2 = ['class']
y = melbourne_data[melbourne_features2]

In [8]:
from sklearn.neighbors import KNeighborsClassifier #Defining 
#from sklearn.metrics import mean_absolute_error

# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = KNeighborsClassifier()

# Fit model
melbourne_model.fit(x, y) #outputs DecisionTreeRegressor(random_state=1)

C:\Users\chinm\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [9]:
print("Making predictions for the following poses:")
print(x.head())
print("The predictions are")
print(melbourne_model.predict(x.head()))

Making predictions for the following poses:
   nose_x  nose_y  neck_x  neck_y  Rshoulder_x  Rshoulder_y  Relbow_x  \
0    0.55    0.46    0.54    0.52         0.51         0.52      0.52
1    0.54    0.46    0.54    0.52         0.51         0.52      0.49
2    0.54    0.46    0.54    0.52         0.51         0.52      0.49
3    0.54    0.46    0.54    0.52         0.51         0.52      0.49
4    0.54    0.46    0.54    0.52         0.51         0.52      0.50

   Relbow_y  Rwrist_x  RWrist_y  ...  LAnkle_x  LAnkle_y  REye_x  REye_y  \
0      0.57      0.54      0.50  ...      0.57      0.91    0.54    0.46
1      0.61      0.50      0.65  ...      0.57      0.91    0.54    0.46
2      0.59      0.50      0.65  ...      0.57      0.91    0.54    0.46
3      0.59      0.50      0.65  ...      0.57      0.91    0.54    0.44
4      0.59      0.51      0.65  ...      0.57      0.91    0.54    0.44

   LEye_x  LEye_y  REar_x  REar_y  LEar_x  LEar_y
0    0.00    0.00    0.52    0.46    0.55    0.46
1    0.55    0.46    0.52    0.46    0.56    0.46
2    0.55    0.46    0.52    0.46    0.56    0.46
3    0.55    0.44    0.52    0.46    0.55    0.46
4    0.55    0.44    0.52    0.46    0.55    0.46

[5 rows x 36 columns]
The predictions are
['wave' 'stand' 'stand' 'stand' 'stand']

In [10]:
y.head()

   class
0  stand
1  stand
2  stand
3  stand
4  stand

In [11]:
x.head()

,nose_x,nose_y,neck_x,neck_y,Rshoulder_x,Rshoulder_y,Relbow_x,Relbow_y,Rwrist_x,RWrist_y,...,LAnkle_x,LAnkle_y,REye_x,REye_y,LEye_x,LEye_y,REar_x,REar_y,LEar_x,LEar_y
0,0.55,0.46,0.54,0.52,0.51,0.52,0.52,0.57,0.54,0.50,...,0.57,0.91,0.54,0.46,0.00,0.00,0.52,0.46,0.55,0.46
1,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.61,0.50,0.65,...,0.57,0.91,0.54,0.46,0.55,0.46,0.52,0.46,0.56,0.46
2,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.59,0.50,0.65,...,0.57,0.91,0.54,0.46,0.55,0.46,0.52,0.46,0.56,0.46
3,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.59,0.50,0.65,...,0.57,0.91,0.54,0.44,0.55,0.44,0.52,0.46,0.55,0.46
4,0.54,0.46,0.54,0.52,0.51,0.52,0.50,0.59,0.51,0.65,...,0.57,0.91,0.54,0.44,0.55,0.44,0.52,0.46,0.55,0.46

In [12]:
from sklearn.model_selection import train_test_split

# split data into training and validation data, for both features and target
# The split is based on a random nu mber generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_x, train_y, val_y = train_test_split(x, y, random_state = 0)
# Define model
#melbourne_model = DecisionTreeRegressor()
# Fit model
#melbourne_model.fit(train_X, train_y)

# get predicted prices on validation data
#val_predictions = melbourne_model.predict(val_x)
#print(mean_absolute_error(val_y, val_predictions))

melbourne_model = KNeighborsClassifier()
melbourne_model.fit(train_X, train_y)
melb_preds = melbourne_model.predict(val_x)
print(melb_preds)

#print(mean_absolute_error(val_y, melb_preds))

['stand' 'walk' 'wave' 'stand' 'stand' 'wave' 'walk' 'squat' 'squat'
 'wave' 'walk' 'squat' 'walk' 'wave' 'squat' 'walk' 'stand' 'squat' 'walk'
 'stand' 'squat' 'walk' 'walk' 'stand' 'stand' 'squat' 'squat' 'stand'
 'walk' 'stand' 'wave' 'wave' 'wave' 'wave' 'stand' 'wave' 'stand' 'wave'
 'squat' 'walk' 'walk' 'stand' 'walk' 'stand' 'stand' 'wave' 'wave' 'walk'
 'stand' 'wave' 'wave' 'squat' 'wave' 'stand' 'stand' 'stand' 'walk'
 'stand' 'stand' 'stand' 'stand' 'wave' 'wave' 'squat' 'walk' 'stand'
 'wave' 'squat' 'stand' 'wave' 'stand' 'squat' 'stand' 'stand' 'wave'
 'wave' 'walk' 'stand' 'wave' 'wave' 'stand' 'stand' 'stand' 'walk'
 'stand' 'squat' 'stand' 'squat' 'squat' 'squat' 'walk' 'squat' 'walk'
 'walk' 'walk' 'stand' 'stand' 'walk' 'squat' 'squat' 'walk' 'stand'
 'wave' 'walk' 'walk' 'wave' 'squat' 'walk' 'walk' 'wave' 'wave' 'wave'
 'wave' 'stand' 'squat' 'squat' 'stand' 'stand' 'walk' 'walk' 'squat'
 'stand' 'wave' 'walk' 'stand' 'walk' 'walk' 'walk' 'stand' 'wave' 'stand'
 'walk' 'walk' 'wave' 'wave' 'stand' 'stand' 'wave' 'wave' 'squat' 'walk'
 'wave' 'walk' 'stand' 'stand' 'squat' 'walk' 'wave' 'walk' 'stand' 'walk'
 'walk' 'squat' 'wave' 'stand' 'wave' 'walk' 'stand' 'stand' 'walk'
 'stand' 'walk' 'wave' 'walk' 'walk' 'stand' 'stand' 'walk' 'stand' 'walk'
 'stand' 'squat' 'stand' 'walk' 'squat' 'wave' 'walk' 'walk' 'squat'
 'wave' 'stand' 'walk' 'stand' 'squat' 'wave' 'squat' 'walk' 'wave' 'walk'
 'walk' 'wave' 'walk' 'walk' 'stand' 'stand' 'wave' 'stand' 'stand' 'wave'
 'stand' 'squat' 'squat' 'walk' 'walk' 'walk' 'squat' 'squat' 'walk'
 'walk' 'walk' 'stand' 'squat' 'squat' 'wave' 'walk' 'stand' 'wave'
 'squat' 'stand' 'squat' 'stand' 'wave' 'wave' 'wave' 'stand' 'wave'
 'wave' 'stand' 'squat' 'squat' 'walk' 'stand' 'squat' 'stand' 'stand'
 'stand' 'wave' 'wave' 'walk' 'squat' 'squat' 'walk' 'walk' 'stand'
 'squat' 'walk' 'wave' 'stand' 'walk' 'wave' 'squat' 'stand' 'walk' 'wave'
 'squat' 'wave' 'squat' 'wave' 'stand' 'stand' 'squat' 'walk' 'walk'
 'walk' 'stand' 'wave' 'squat' 'walk' 'stand' 'stand' 'wave' 'squat'
 'stand' 'stand' 'wave' 'squat' 'walk' 'wave' 'stand' 'walk' 'squat'
 'stand' 'stand' 'squat' 'walk' 'wave' 'squat' 'wave' 'walk' 'wave'
 'stand' 'stand' 'walk' 'wave' 'walk' 'squat' 'walk' 'walk' 'squat' 'wave'
 'wave' 'walk' 'wave' 'stand' 'squat' 'stand' 'walk' 'wave' 'walk' 'squat'
 'squat' 'walk' 'wave' 'stand' 'walk' 'wave' 'squat' 'wave' 'stand' 'wave'
 'squat' 'walk' 'squat' 'walk' 'squat' 'walk' 'stand' 'walk' 'stand'
 'walk' 'squat' 'walk' 'walk' 'walk' 'wave' 'wave' 'walk' 'walk' 'wave'
 'stand' 'walk' 'walk' 'wave' 'stand' 'stand' 'squat' 'squat' 'walk'
 'wave' 'wave' 'stand' 'walk' 'wave' 'squat' 'squat' 'stand' 'squat'
 'wave' 'squat' 'squat' 'squat' 'wave' 'stand' 'stand' 'wave' 'squat'
 'squat' 'walk' 'wave' 'walk' 'stand' 'wave' 'stand' 'wave' 'walk' 'walk'
 'wave' 'squat' 'squat' 'squat' 'squat' 'squat' 'stand' 'walk' 'squat'
 'wave' 'squat' 'squat' 'wave' 'squat' 'wave' 'stand' 'squat' 'squat'
 'squat' 'squat' 'squat' 'walk' 'wave' 'wave' 'walk' 'squat' 'wave'
 'stand' 'wave' 'stand' 'walk' 'stand' 'wave' 'walk' 'stand' 'wave' 'walk'
 'stand' 'wave' 'stand' 'wave' 'stand' 'walk' 'walk' 'squat' 'wave' 'walk'
 'squat' 'wave' 'wave' 'squat' 'stand' 'stand' 'walk' 'stand' 'squat'
 'wave' 'wave' 'squat' 'squat' 'walk' 'walk' 'squat' 'walk' 'stand' 'wave'
 'stand' 'walk' 'wave' 'stand' 'stand' 'wave' 'stand' 'wave' 'stand'
 'squat' 'walk' 'wave' 'stand' 'stand' 'walk' 'stand' 'stand' 'stand'
 'stand' 'walk' 'wave' 'stand' 'stand' 'wave' 'walk' 'walk' 'wave' 'stand'
 'stand' 'wave' 'stand' 'stand' 'wave' 'wave' 'wave' 'stand' 'stand'
 'stand' 'squat' 'squat' 'stand' 'stand' 'squat' 'squat' 'squat' 'stand'
 'walk' 'wave' 'wave' 'squat' 'squat' 'stand' 'squat' 'stand' 'squat'
 'stand' 'stand' 'stand' 'walk' 'walk' 'squat' 'walk' 'walk' 'walk'
 'squat' 'wave' 'walk' 'wave' 'walk' 'squat' 'stand' 'wave' 'stand' 'walk'
 'stand' 'walk' 'squat' 'walk' 'squat' 'walk' 'wave' 'walk' 'squat'
 'stand' 'wave' 'stand' 'stand' 'squat' 'wave' 'walk' 'stand' 'stand'
 'squat' 'wave' 'stand' 'wave' 'squat' 'walk' 'squat' 'wave' 'squat'
 'wave' 'stand' 'squat' 'walk' 'stand' 'wave' 'squat' 'squat' 'stand'
 'walk' 'wave' 'walk' 'squat' 'wave' 'squat' 'squat' 'stand' 'walk'
 'stand' 'stand' 'wave' 'stand' 'walk' 'wave' 'walk' 'stand' 'squat'
 'squat' 'stand' 'squat' 'squat' 'squat' 'squat' 'squat' 'stand' 'walk'
 'stand' 'squat' 'wave' 'wave' 'squat' 'walk' 'walk' 'walk' 'stand' 'wave'
 'walk' 'walk' 'squat' 'squat' 'wave' 'stand' 'squat' 'wave' 'wave'
 'squat' 'wave' 'walk' 'stand' 'squat' 'squat' 'stand' 'stand' 'squat'
 'stand' 'stand' 'stand' 'wave' 'squat' 'walk' 'stand' 'stand' 'wave'
 'squat' 'walk' 'squat' 'wave' 'stand' 'wave' 'wave' 'wave' 'wave' 'walk'
 'walk' 'walk' 'stand' 'wave' 'walk' 'stand' 'walk' 'stand' 'walk' 'squat'
 'wave' 'walk' 'wave' 'stand' 'stand' 'walk' 'squat' 'walk' 'walk' 'squat'
 'walk' 'walk' 'walk' 'stand' 'squat' 'wave' 'squat' 'wave' 'walk' 'wave'
 'walk' 'walk' 'stand' 'walk' 'stand' 'walk' 'squat' 'wave' 'wave' 'squat'
 'squat' 'squat' 'squat' 'walk' 'walk' 'walk' 'walk' 'stand' 'squat'
 'walk' 'walk' 'walk' 'stand' 'stand' 'walk' 'squat' 'wave' 'stand' 'walk'
 'stand' 'wave' 'wave' 'wave' 'walk' 'wave' 'stand' 'wave' 'walk' 'wave'
 'wave' 'stand' 'wave' 'wave' 'wave' 'walk' 'walk' 'walk' 'walk' 'squat'
 'squat' 'stand']

C:\Users\chinm\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [19]:
x

,nose_x,nose_y,neck_x,neck_y,Rshoulder_x,Rshoulder_y,Relbow_x,Relbow_y,Rwrist_x,RWrist_y,...,LAnkle_x,LAnkle_y,REye_x,REye_y,LEye_x,LEye_y,REar_x,REar_y,LEar_x,LEar_y
0,0.55,0.46,0.54,0.52,0.51,0.52,0.52,0.57,0.54,0.50,...,0.57,0.91,0.54,0.46,0.00,0.00,0.52,0.46,0.55,0.46
1,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.61,0.50,0.65,...,0.57,0.91,0.54,0.46,0.55,0.46,0.52,0.46,0.56,0.46
2,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.59,0.50,0.65,...,0.57,0.91,0.54,0.46,0.55,0.46,0.52,0.46,0.56,0.46
3,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.59,0.50,0.65,...,0.57,0.91,0.54,0.44,0.55,0.44,0.52,0.46,0.55,0.46
4,0.54,0.46,0.54,0.52,0.51,0.52,0.50,0.59,0.51,0.65,...,0.57,0.91,0.54,0.44,0.55,0.44,0.52,0.46,0.55,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2821,0.48,0.39,0.48,0.46,0.45,0.46,0.42,0.39,0.44,0.28,...,0.54,0.96,0.46,0.37,0.49,0.37,0.45,0.39,0.50,0.37
2822,0.48,0.39,0.48,0.46,0.44,0.46,0.40,0.39,0.40,0.31,...,0.54,0.96,0.46,0.37,0.48,0.37,0.45,0.39,0.49,0.37
2823,0.46,0.39,0.46,0.46,0.43,0.46,0.38,0.44,0.34,0.35,...,0.54,0.96,0.46,0.37,0.48,0.37,0.45,0.37,0.49,0.37
2824,0.46,0.39,0.46,0.46,0.43,0.46,0.38,0.46,0.33,0.39,...,0.52,0.98,0.46,0.37,0.48,0.37,0.45,0.37,0.49,0.37
2825,0.46,0.37,0.46,0.46,0.43,0.46,0.38,0.52,0.34,0.50,...,0.51,0.98,0.46,0.37,0.48,0.37,0.44,0.37,0.49,0.37

[0.55, 0.46, 0.54, 0.52, 0.51, 0.52, 0.52, 0.57, 0.54, 0.5, 0.56, 0.52, 0.57, 0.59, 0.59, 0.65, 0.52, 0.67, 0.52, 0.81, 0.52, 0.89, 0.56, 0.67, 0.57, 0.81, 0.57, 0.91, 0.54, 0.46, 0.0, 0.0, 0.52, 0.46, 0.55, 0.46]

In [13]:
melb_preds2 = melbourne_model.predict(x)
print(melb_preds2)

['wave' 'stand' 'stand' ... 'wave' 'wave' 'wave']

In [15]:
a = {'nose_x' :[0.55] , 'nose_y' : [0.46], 'neck_x': [0.54] , 'neck_y' : [0.52], 'Rshoulder_x' : [0.51] , 'Rshoulder_y' : [0.52],
       'Relbow_x' : [0.52], 'Relbow_y' : [0.57], 'Rwrist_x' : [0.54], 'RWrist_y' : [0.5], 'LShoulder_x' : [0.56],
       'LShoulder_y' : [0.52], 'LElbow_x' : [0.57], 'LElbow_y' : [0.59], 'LWrist_x' : [0.59], 'LWrist_y' : [0.65] , 'RHip_x' : [0.52],
       'RHip_y' : [0.67], 'RKnee_x' : [0.52], 'RKnee_y' : [0.81], 'RAnkle_x' : [0.52] , 'RAnkle_y' : [0.89], 'LHip_x' :[0.56] ,
       'LHip_y' : [0.67] , 'LKnee_x' : [0.57], 'LKnee_y' :[0.81] , 'LAnkle_x' : [0.57], 'LAnkle_y' : [0.91], 'REye_x' : [0.54],
       'REye_y' : [0.46], 'LEye_x' : [0.0], 'LEye_y' : [0.0], 'REar_x' :[0.52] , 'REar_y' : [0.46], 'LEar_x' : [0.55] , 'LEar_y' : [0.46]}

In [16]:
new = pd.DataFrame(a)
melb_preds2 = melbourne_model.predict(new)
print(melb_preds2)

['wave']

In [ ]:
#shoulder = [landmarks[mp_pose.PoseLandmark.nose_x.value].x , landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].y]

a = {'nose_x' :[landmarks[mp_pose.PoseLandmark.Nose.value].x] , 'nose_y' : [landmarks[mp_pose.PoseLandmark.Nose.value].y], 'neck_x': [landmarks[mp_pose.PoseLandmark.Left_eye_inner.value].x] , 
     'neck_y' : [landmarks[mp_pose.PoseLandmark.Left_eye_inner.value].y], 'Rshoulder_x' : [landmarks[mp_pose.PoseLandmark.right_shoulder.value].x] , 'Rshoulder_y' : [landmarks[mp_pose.PoseLandmark.right_shoulder.value].x],
       'Relbow_x' : [landmarks[mp_pose.PoseLandmark.right_shoulder.value].x], 'Relbow_y' : [landmarks[mp_pose.PoseLandmark.right_shoulder.value].x], 'Rwrist_x' : [landmarks[mp_pose.PoseLandmark.right_wrist.value].x], 'RWrist_y' : [landmarks[mp_pose.PoseLandmark.right_wrist.value].x], 'LShoulder_x' : [landmarks[mp_pose.PoseLandmark.left_shoulder.value].x],
       'LShoulder_y' : [landmarks[mp_pose.PoseLandmark.left_shoulder.value].x], 'LElbow_x' : [landmarks[mp_pose.PoseLandmark.left_elbow.value].x], 'LElbow_y' : [landmarks[mp_pose.PoseLandmark.left_elbow.value].x], 'LWrist_x' : [landmarks[mp_pose.PoseLandmark.left_wrist.value].x], 'LWrist_y' : [landmarks[mp_pose.PoseLandmark.left_wrist.value].x] , 'RHip_x' : [landmarks[mp_pose.PoseLandmark.right_hip.value].x],
       'RHip_y' : [landmarks[mp_pose.PoseLandmark.right_hip.value].x], 'RKnee_x' : [landmarks[mp_pose.PoseLandmark.right_knee.value].x], 'RKnee_y' : [landmarks[mp_pose.PoseLandmark.right_knee.value].x], 'RAnkle_x' : [landmarks[mp_pose.PoseLandmark.right_ankle.value].x] , 'RAnkle_y' : [landmarks[mp_pose.PoseLandmark.right_ankle.value].x], 'LHip_x' :[landmarks[mp_pose.PoseLandmark.left_hip.value].x] ,
       'LHip_y' : [landmarks[mp_pose.PoseLandmark.left_hip.value].x] , 'LKnee_x' : [landmarks[mp_pose.PoseLandmark.left_knee.value].x], 'LKnee_y' :[landmarks[mp_pose.PoseLandmark.left_knee.value].x] , 'LAnkle_x' : [landmarks[mp_pose.PoseLandmark.left_ankle.value].x], 'LAnkle_y' : [landmarks[mp_pose.PoseLandmark.left_ankle.value].x], 'REye_x' : [landmarks[mp_pose.PoseLandmark.right_eye.value].x],
       'REye_y' : [landmarks[mp_pose.PoseLandmark.right_eye.value].x], 'LEye_x' : [landmarks[mp_pose.PoseLandmark.left_eye.value].x], 'LEye_y' : [landmarks[mp_pose.PoseLandmark.left_eye.value].x], 'REar_x' :[landmarks[mp_pose.PoseLandmark.right_ear.value].x] , 'REar_y' : [landmarks[mp_pose.PoseLandmark.right_ear.value].x], 'LEar_x' : [landmarks[mp_pose.PoseLandmark.left_ear.value].x] , 'LEar_y' : [landmarks[mp_pose.PoseLandmark.left_ear.value].x]}
       
ourdata = pd.DataFrame(a)

melb_preds2 = forest_model.predict(ourdata)
print(melb_preds2)

In [92]:
x

,nose_x,nose_y,neck_x,neck_y,Rshoulder_x,Rshoulder_y,Relbow_x,Relbow_y,Rwrist_x,RWrist_y,...,LAnkle_x,LAnkle_y,REye_x,REye_y,LEye_x,LEye_y,REar_x,REar_y,LEar_x,LEar_y
0,0.55,0.46,0.54,0.52,0.51,0.52,0.52,0.57,0.54,0.50,...,0.57,0.91,0.54,0.46,0.00,0.00,0.52,0.46,0.55,0.46
1,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.61,0.50,0.65,...,0.57,0.91,0.54,0.46,0.55,0.46,0.52,0.46,0.56,0.46
2,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.59,0.50,0.65,...,0.57,0.91,0.54,0.46,0.55,0.46,0.52,0.46,0.56,0.46
3,0.54,0.46,0.54,0.52,0.51,0.52,0.49,0.59,0.50,0.65,...,0.57,0.91,0.54,0.44,0.55,0.44,0.52,0.46,0.55,0.46
4,0.54,0.46,0.54,0.52,0.51,0.52,0.50,0.59,0.51,0.65,...,0.57,0.91,0.54,0.44,0.55,0.44,0.52,0.46,0.55,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2822,0.48,0.39,0.48,0.46,0.44,0.46,0.40,0.39,0.40,0.31,...,0.54,0.96,0.46,0.37,0.48,0.37,0.45,0.39,0.49,0.37
2823,0.46,0.39,0.46,0.46,0.43,0.46,0.38,0.44,0.34,0.35,...,0.54,0.96,0.46,0.37,0.48,0.37,0.45,0.37,0.49,0.37
2824,0.46,0.39,0.46,0.46,0.43,0.46,0.38,0.46,0.33,0.39,...,0.52,0.98,0.46,0.37,0.48,0.37,0.45,0.37,0.49,0.37
2825,0.46,0.37,0.46,0.46,0.43,0.46,0.38,0.52,0.34,0.50,...,0.51,0.98,0.46,0.37,0.48,0.37,0.44,0.37,0.49,0.37
2828,0.55,0.46,0.54,0.52,0.51,0.52,0.52,0.57,0.54,0.50,...,0.57,0.91,0.54,0.46,0.00,0.00,0.52,0.46,0.55,0.46

In [36]:
#x.drop(x.columns[[2]] , axis = 1 , inplace = True)
#x.drop(x.columns[[2]] , axis = 1 , inplace = True)